config/routes.rb
AwsBillingRegister::Application.routes.draw do
  resources :accounts do
    resources :reports, only: [:index, :show]
  end

  root "accounts#index"
end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :reports

  def s3
    @s3 ||= AWS::S3.new(
      access_key_id:      access_key_id,
      secret_access_key:  secret_access_key,
      region:             region
    )
  end

  def bucket
    s3.buckets[bucket_name] or
      raise "No bucket named `#{bucket_name}` for account `#{name}`"
  end

  def cost_allocation_csv_objects
    prefix = "#{account_id}-aws-cost-allocation-"
    bucket.objects.with_prefix(prefix)
  end

  def find_or_initialize_report_for_s3object(s3object)
    if match = /-(\d{4})-(\d{2})\.csv$/.match(s3object.key)
      year  = match[1]
      month = match[2]
      reports.where(year: year, month: month).first_or_initialize
    else
      raise "missmatch: #{s3object.key}"
    end
  end
end

app/models/availability_zone.rb
class AvailabilityZone < ActiveRecord::Base
end

app/models/cost_allocation.rb
class CostAllocation < ActiveRecord::Base
  belongs_to :report
  belongs_to :product
  belongs_to :usage_type
  belongs_to :availability_zone
end

app/models/csv_register.rb
require "csv"

class CsvRegister
  def self.execute!(report, csv_string)
    new(report).execute!(csv_string)
  end

  def initialize(report)
    @report = report
  end

  def execute!(csv_string)
    csv_string = cleanup_csv_string(csv_string)
    csv = CSV.parse(csv_string, headers: true)

    register_user_tags(csv.headers)
    register_records(csv)
    update_totals!(csv)
  end

  private

    def cleanup_csv_string(csv_string)
      lines = csv_string.split(/\n/)

      x_lines = []
      flag = false
      lines.each do |line|
        flag = flag || line =~ /^InvoiceID/
        x_lines << line if flag
      end

      x_lines.join("\n")
    end

    def register_user_tags(csv_headers)
      csv_headers.each do |header|
        next unless match = header.match(/^user:(.+)/) and tag_name = match[1]
        # create Tag record
      end
    end

    def register_records(csv)
      csv.each do |row|
        break if row["InvoiceID"].blank?
        next unless row["RecordType"] == "PayerLineItem"
        register_record(row)
      end
    end

    def register_record(row)
      @report.cost_allocations.where(record_id: row["RecordID"]).first_or_create! do |cost_allocation|
        cost_allocation.billing_period_start_date = parse_time(row["BillingPeriodStartDate"])
        cost_allocation.billing_period_end_date   = parse_time(row["BillingPeriodEndDate"])
        cost_allocation.invoice_date              = parse_time(row["InvoiceDate"])
        cost_allocation.product                   = product(row["ProductCode"], row["ProductName"])
        cost_allocation.usage_type                = usage_type(row["UsageType"])
        cost_allocation.availability_zone         = availability_zone(row["AvailabilityZone"])
        cost_allocation.usage_quantity            = row["UsageQuantity"]
        cost_allocation.total_cost                = row["TotalCost"].to_f
      end
    end

    def parse_time(time_string)
      ActiveSupport::TimeZone["UTC"].parse(time_string)
    end

    def product(code, name)
      Product.where(code: code).first_or_create! do |product|
        product.name = name
      end
    end

    def usage_type(name)
      UsageType.where(name: name).first_or_create!
    end

    def availability_zone(name)
      AvailabilityZone.where(name: name).first_or_create!
    end

    def update_totals!(csv)
      csv.each do |row|
        case record_id = row["RecordID"]
        when "InvoiceTotal:Estimated"
          @report.invoice_total = row["TotalCost"].to_f
        when "StatementTotal"
          @report.statement_total = row["TotalCost"].to_f
        else
          break if record_id.blank?
        end
      end

      @report.save!
    end
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :account
  has_many :cost_allocations

  def date
    persisted? ? Date.new(year, month) : nil
  end
end

app/models/usage_type.rb
class UsageType < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render action: 'show', status: :created, location: @account }
      else
        format.html { render action: 'new' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :account_id, :access_key_id, :secret_access_key, :region, :bucket_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  helper_method :account

  def index
    @reports = account.reports.includes(cost_allocations: [:product, :usage_type, :availability_zone])
    @report = @reports.last
  end

  def show
    @reports = account.reports.includes(cost_allocations: [:product, :usage_type, :availability_zone])
    @report = @reports.find(params[:id])
  end

  private

    def account
      @account ||= Account.find(params[:account_id])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/accounts/_form.html.slim
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      h2 = "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      ul
        - @account.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :account_id
    = f.text_field :account_id
  .field
    = f.label :access_key_id
    = f.text_field :access_key_id
  .field
    = f.label :secret_access_key
    = f.text_field :secret_access_key
  .field
    = f.label :region
    = f.text_field :region
  .field
    = f.label :bucket_name
    = f.text_field :bucket_name
  .actions = f.submit 'Save'

app/views/accounts/edit.html.slim
h1 Editing account

== render 'form'

= link_to 'Show', @account
'|
= link_to 'Back', accounts_path

app/views/accounts/index.html.slim
h1 Listing accounts

table
  tr
    th.header Name
    th.header AccountID
    th.header
    th.header
    th.header
    th.header

  - @accounts.each do |account|
    tr
      td = account.name
      td = account.account_id
      td = link_to 'Report', account_reports_path(account)
      td = link_to 'Show', account
      td = link_to 'Edit', edit_account_path(account)
      td = link_to 'Destroy', account, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.slim
h1 New account

== render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.slim
p#notice = notice

p
  strong Name:
  = @account.name
p
  strong Account:
  = @account.account_id
p
  strong Access key:
  = @account.access_key_id
p
  strong Secret access key:
  = @account.secret_access_key
p
  strong Region:
  = @account.region
p
  strong Bucket name:
  = @account.bucket_name

= link_to 'Edit', edit_account_path(@account)
'|
= link_to 'Back', accounts_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwsBillingRegister</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/_list.html.slim
h2 reports

ul
  - @reports.each do |report|
    li = link_to report.date.strftime("%Y-%m"), account_report_path(account, report)

app/views/reports/index.html.slim
h1 = account.name

#chart data-reports="#{@reports.map { |r| { ym: r.date.strftime("%Y-%m"),  statement_total: r.statement_total } }.to_json}"

h2 reports

table.table
  thead
    tr
      th.header Y-m
      th.header Statement Total
      th.header LastModified
      th.header

  tbody
    - @reports.each do |report|
      tr
        td = report.date.strftime("%Y-%m")
        td = report.statement_total
        td = report.last_modified
        td = link_to "Show", account_report_path(account, report)

javascript:
  $(function() {
    Morris.Line({
      element: "chart",
      data: $("#chart").data("reports"),
      xkey: "ym",
      ykeys: ["statement_total"],
      labels: ["Statement Total"],
      xLabels: "month"
    });
  });

app/views/reports/show.html.slim
h1 #{account.name} / #{@report.date.strftime("%Y-%m")}

table.table
  thead
    tr
      th.header RecordID
      th.header ProductCode
      th.header UsageType
      th.header AZ
      th.header UsageQuantity
      th.header TotalCost

  tfoot
    tr
      td colspan="5" Statement Total
      td = @report.statement_total

  tbody
    - @report.cost_allocations.each do |cost_allocation|
      tr
        td = cost_allocation.record_id
        td = cost_allocation.product.code
        td = cost_allocation.usage_type.name
        td = cost_allocation.availability_zone.name
        td = cost_allocation.usage_quantity
        td = cost_allocation.total_cost

== render partial: "list"